name: check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: npx zx --experimental .github/scripts/coverage.mjs
